-- 清理原有对应字典的旧数据，避免冲突
DELETE FROM sys_dict_data WHERE dict_type IN ('water_station_type', 'water_device_type', 'water_point_type');

-- 1. 插入站点类型数据 (water_station_type)
INSERT INTO sys_dict_data (dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, remark) VALUES
(1, '站点类型根节点', 'STATION_ROOT', 'water_station_type', '', 'default', 'N', '0', 'admin', NOW(), '所有站点类型的根节点'),
(2, '厂站', 'WATER_SUPPLY', 'water_station_type', '', 'primary', 'Y', '0', 'admin', NOW(), '负责供水的站点'),
(3, '管网监测', 'MONITOR', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '负责数据监测的站点'),
(4, '控制类站点', 'CONTROL', 'water_station_type', '', 'warning', 'N', '0', 'admin', NOW(), '负责设备控制的站点'),
(5, '其他类站点', 'OTHER', 'water_station_type', '', 'info', 'N', '0', 'admin', NOW(), '其他类型站点'),
(6, '水厂', 'WATER_PLANT', 'water_station_type', '', 'primary', 'N', '0', 'admin', NOW(), '原水/净水厂'),
(7, '泵站', 'PUMP_STATION', 'water_station_type', '', 'primary', 'N', '0', 'admin', NOW(), '加压泵站/提升泵站'),
(8, '二次供水站', 'SECONDARY_SUPPLY', 'water_station_type', '', 'primary', 'N', '0', 'admin', NOW(), '小区/楼宇二供站'),
(9, '调压站', 'REGULATOR_STATION', 'water_station_type', '', 'primary', 'N', '0', 'admin', NOW(), '管网调压站'),
(16, '环境监测点', 'ENVIRONMENT_MONITOR', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '环境参数监测点'),
(17, '阀门控制站', 'VALVE_CONTROL_STATION', 'water_station_type', '', 'warning', 'N', '0', 'admin', NOW(), '管网阀门控制站'),
(18, '水泵控制站', 'PUMP_CONTROL_STATION', 'water_station_type', '', 'warning', 'N', '0', 'admin', NOW(), '水泵集群控制站'),
(19, '维保站点', 'MAINTENANCE_STATION', 'water_station_type', '', 'info', 'N', '0', 'admin', NOW(), '设备维保临时站点'),
(20, '测试站点', 'TEST_STATION', 'water_station_type', '', 'info', 'N', '0', 'admin', NOW(), '系统测试站点'),
(21, '流量监测点', 'PIPE_NETWORK_MONITOR_FLOW', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), ''),
(22, '流量计', 'PIPE_NETWORK_MONITOR_FLOW_1', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '流量监测点'),
(23, '复核表', 'PIPE_NETWORK_MONITOR_FLOW_2', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '流量监测点'),
(24, '二供复核表', 'PIPE_NETWORK_MONITOR_FLOW_3', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '流量监测点'),
(25, '计费表', 'PIPE_NETWORK_MONITOR_FLOW_4', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '流量监测点'),
(26, '其他', 'PIPE_NETWORK_MONITOR_FLOW_5', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '流量监测点'),
(27, '压力监测点', 'PIPE_NETWORK_MONITOR_PRESSURE', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '管网压力'),
(28, '水质监测点', 'QUALITY_MONITOR', 'water_station_type', '', 'success', 'N', '0', 'admin', NOW(), '水质在线监测点');


-- 2. 插入设备类型数据 (water_device_type)
INSERT INTO sys_dict_data (dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, remark) VALUES
(1, '水泵类', 'PUMP', 'water_device_type', '', 'primary', 'Y', '0', 'admin', NOW(), '水泵设备分类'),
(2, '阀门类', 'VALVE', 'water_device_type', '', 'success', 'N', '0', 'admin', NOW(), '阀门设备分类'),
(3, '电机类', 'MOTOR', 'water_device_type', '', 'warning', 'N', '0', 'admin', NOW(), '电机设备分类'),
(4, '仪表类', 'INSTRUMENT', 'water_device_type', '', 'info', 'N', '0', 'admin', NOW(), '仪表设备分类'),
(5, '电气类', 'ELECTRIC', 'water_device_type', '', 'danger', 'N', '0', 'admin', NOW(), '电气设备分类'),
(6, '加药设备类', 'CHEMICAL', 'water_device_type', '', 'default', 'N', '0', 'admin', NOW(), '加药设备分类'),
(7, '水处理设备类', 'TREATMENT', 'water_device_type', '', 'primary', 'N', '0', 'admin', NOW(), '水处理设备分类'),
(8, '其他设备类', 'OTHER', 'water_device_type', '', 'info', 'N', '0', 'admin', NOW(), '其他设备分类'),
(9, '离心泵', 'PUMP_CENTRIFUGAL', 'water_device_type', '', 'primary', 'N', '0', 'admin', NOW(), '离心泵'),
(10, '潜水泵', 'PUMP_SUBMERSIBLE', 'water_device_type', '', 'primary', 'N', '0', 'admin', NOW(), '潜水泵'),
(11, '增压泵', 'PUMP_BOOSTER', 'water_device_type', '', 'primary', 'N', '0', 'admin', NOW(), '增压泵'),
(12, '加药泵', 'PUMP_DOSING', 'water_device_type', '', 'primary', 'N', '0', 'admin', NOW(), '加药泵'),
(13, '蝶阀', 'VALVE_BUTTERFLY', 'water_device_type', '', 'success', 'N', '0', 'admin', NOW(), '蝶阀'),
(14, '闸阀', 'VALVE_GATE', 'water_device_type', '', 'success', 'N', '0', 'admin', NOW(), '闸阀'),
(15, '球阀', 'VALVE_BALL', 'water_device_type', '', 'success', 'N', '0', 'admin', NOW(), '球阀'),
(16, '止回阀', 'VALVE_CHECK', 'water_device_type', '', 'success', 'N', '0', 'admin', NOW(), '止回阀'),
(17, '减压阀', 'VALVE_PRESSURE_REDUCING', 'water_device_type', '', 'success', 'N', '0', 'admin', NOW(), '减压阀'),
(18, '流量仪表', 'INSTRUMENT_FLOW', 'water_device_type', '', 'info', 'N', '0', 'admin', NOW(), '流量仪表'),
(19, '压力仪表', 'INSTRUMENT_PRESSURE', 'water_device_type', '', 'info', 'N', '0', 'admin', NOW(), '压力仪表'),
(20, '液位仪表', 'INSTRUMENT_LEVEL', 'water_device_type', '', 'info', 'N', '0', 'admin', NOW(), '液位仪表'),
(21, '水质仪表', 'INSTRUMENT_QUALITY', 'water_device_type', '', 'info', 'N', '0', 'admin', NOW(), '水质仪表'),
(22, '电动机', 'ELECTRIC_MOTOR', 'water_device_type', '', 'danger', 'N', '0', 'admin', NOW(), '电动机'),
(23, '变压器', 'ELECTRIC_TRANSFORMER', 'water_device_type', '', 'danger', 'N', '0', 'admin', NOW(), '变压器'),
(24, '配电柜', 'ELECTRIC_CABINET', 'water_device_type', '', 'danger', 'N', '0', 'admin', NOW(), '配电柜');


-- 3. 插入测点类型数据 (water_point_type)
INSERT INTO sys_dict_data (dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, remark) VALUES
(1, '压力参数', 'PRESSURE', 'water_point_type', '', 'primary', 'Y', '0', 'admin', NOW(), '压力相关测点'),
(2, '流量参数', 'FLOW', 'water_point_type', '', 'success', 'N', '0', 'admin', NOW(), '流量相关测点'),
(3, '液位参数', 'LEVEL', 'water_point_type', '', 'warning', 'N', '0', 'admin', NOW(), '液位相关测点'),
(4, '水质参数', 'QUALITY', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '水质相关测点'),
(5, '电气参数', 'ELECTRIC', 'water_point_type', '', 'danger', 'N', '0', 'admin', NOW(), '电气相关测点'),
(6, '状态参数', 'STATUS', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '设备状态测点'),
(7, '控制参数', 'CONTROL', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '控制相关测点'),
(8, '其他参数', 'OTHER', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '其他测点'),
(9, '进水压力', 'PRESSURE_INLET', 'water_point_type', '', 'primary', 'N', '0', 'admin', NOW(), '进水压力测点'),
(10, '出水压力', 'PRESSURE_OUTLET', 'water_point_type', '', 'primary', 'N', '0', 'admin', NOW(), '出水压力测点'),
(11, '管网压力', 'PRESSURE_PIPE', 'water_point_type', '', 'primary', 'N', '0', 'admin', NOW(), '管网压力测点'),
(12, '进水流量', 'FLOW_INLET', 'water_point_type', '', 'success', 'N', '0', 'admin', NOW(), '进水流量测点'),
(13, '出水流量', 'FLOW_OUTLET', 'water_point_type', '', 'success', 'N', '0', 'admin', NOW(), '出水流量测点'),
(14, '累计流量', 'FLOW_TOTAL', 'water_point_type', '', 'success', 'N', '0', 'admin', NOW(), '累计流量测点'),
(15, '清水池液位', 'LEVEL_TANK', 'water_point_type', '', 'warning', 'N', '0', 'admin', NOW(), '清水池液位测点'),
(16, '吸水井液位', 'LEVEL_WELL', 'water_point_type', '', 'warning', 'N', '0', 'admin', NOW(), '吸水井液位测点'),
(17, '浊度', 'QUALITY_TURBIDITY', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '浊度测点'),
(18, '余氯', 'QUALITY_CHLORINE', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '余氯测点'),
(19, 'pH值', 'QUALITY_PH', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), 'pH值测点'),
(20, '电流', 'ELECTRIC_CURRENT', 'water_point_type', '', 'danger', 'N', '0', 'admin', NOW(), '电流测点'),
(21, '电压', 'ELECTRIC_VOLTAGE', 'water_point_type', '', 'danger', 'N', '0', 'admin', NOW(), '电压测点'),
(22, '功率', 'ELECTRIC_POWER', 'water_point_type', '', 'danger', 'N', '0', 'admin', NOW(), '功率测点'),
(23, '运行状态', 'STATUS_RUN', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '运行状态测点'),
(24, '故障状态', 'STATUS_FAULT', 'water_point_type', '', 'danger', 'N', '0', 'admin', NOW(), '故障状态测点'),
(25, '运行模式', 'STATUS_MODE', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '运行模式测点'),
(26, '频率', 'OTHER_FREQ', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '频率测点'),
(27, '转速', 'OTHER_SPEED', 'water_point_type', '', 'default', 'N', '0', 'admin', NOW(), '转速测点'),
(28, '原水浊度', 'IN_QUALITY_TURBIDITY', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '浊度测点'),
(29, '原水余氯', 'IN_QUALITY_CHLORINE', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '余氯测点'),
(30, '原水pH值', 'IN_QUALITY_PH', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), 'pH值测点'),
(31, '出水浊度', 'OUT_QUALITY_TURBIDITY', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '浊度测点'),
(32, '出水余氯', 'OUT_QUALITY_CHLORINE', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '余氯测点'),
(33, '出水pH值', 'OUT_QUALITY_PH', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), 'pH值测点'),
(34, '原水锰离子', 'IN_QUALITY_MENG', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '原水锰离子'),
(35, '原水液位', 'IN_QUALITY_YEWEI', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '原水液位'),
(36, '原水氨氮', 'IN_QUALITY_ANDAN', 'water_point_type', '', 'info', 'N', '0', 'admin', NOW(), '原水氨氮'),
(37, '电耗', 'ELECTRIC_DIANHAO', 'water_point_type', '', 'danger', 'N', '0', 'admin', NOW(), '电耗');